# Generated by Django 3.2.7 on 2021-09-19 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison', models.CharField(max_length=100)),
                ('num_pixels_hex', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/', verbose_name='Картинка')),
                ('hex_code', models.CharField(max_length=7, verbose_name='Hex-код')),
            ],
        ),
    ]
